[project]
enable_telemetry = true
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
enabled = true
accept = ["image/*", "application/pdf"]
max_files = 10
max_size_mb = 50

[UI]
name = "Digital Mufti"
#custom_css = "/public/custom.css"
logo = "/public/logo.png"
favicon = "/public/logo.png"
cot = "full"
default_theme = "light"
layout = "wide"
default_sidebar_state = "open"

[[UI.header_links]]
name = "Download"
display_name = "Download App"
icon_url = "https://img.icons8.com/color/48/android-os.png"
url = "https://www.mediafire.com/file/bt4y9aqhkjqlaqh/Digital_Mufti_1_1.0.apk/file"

[meta]
generated_by = "2.5.5"
